<?php

/**
 * @file
 * Primarily Drupal hooks and global API functions to manipulate views.
 */

use Drupal\Component\Render\MarkupInterface;
use Drupal\Component\Utility\Html;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;


/**
 * Implements hook_help().
 */
function intergrupo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.intergrupo':
      return 'Este funciona para generar citas, contruido por entidades (entity->api)';
  }
}